name: docs
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
            - name: Test GDAL installation
              run: |
                  python -c "from osgeo import gdal"
                  gdalinfo --version
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --user --no-cache-dir Cython
                  pip install codespell -r requirements.txt -r requirements_dev.txt
                  pip install .
            - name: Discover typos with codespell
              run: codespell --skip="*.csv,*.geojson" --ignore-words-list="aci,acount,acounts,fallow,hart,hist,nd,ned,ois,wqs,watermask"
            - name: LOAD EE CREDENTIALS
              run: python ./.github/ee_token.py
              env:
                  EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
            - name: GEEMAP-TEST
              run: |
                  python -m unittest discover tests/
            - run: pip install -r requirements_docs.txt
            - run: mkdocs gh-deploy --force
              env:
                  USE_FOLIUM: ${{ secrets.USE_FOLIUM }}
